'use server';

import { supabase } from '@/lib/supabase';
import { getSession } from '@/lib/session';

import { QUESTIONS } from '@/data/content';

export interface SubmitNiyamPayload {
  date: string;
  completedQuestionIds: string[];
}

export async function submitDailyNiyam(payload: SubmitNiyamPayload) {
  try {
    const userId = await getSession();
    if (!userId) {
      return { success: false, error: 'Unauthorized. Please log in.' };
    }

    const { date, completedQuestionIds } = payload;

    // 1. Fetch current stats (or initialize if missing)
    let { data: stats, error: statsFetchError } = await supabase
      .from('user_stats')
      .select('*')
      .eq('user_id', userId)
      .maybeSingle();

    if (!stats) {
      // Create initial stats if none exist
      const defaultStats = {
        user_id: userId,
        total_xp: 0,
        current_streak: 0,
        best_streak: 0,
        days_completed: 0,
        tree_stage: 0,
        last_submission_date: null,
        updated_at: new Date().toISOString()
      };
      const { data: createdStats, error: createErr } = await supabase
        .from('user_stats')
        .insert(defaultStats)
        .select()
        .single();

      if (createErr || !createdStats) {
        console.error('Error creating default user stats:', createErr);
        // Use fallback memory stats
        stats = defaultStats;
      } else {
        stats = createdStats;
      }
    }

    if (stats.last_submission_date === date) {
      return { success: false, error: 'You have already submitted your Niyam for this date.' };
    }

    // 2. SERVER-SIDE CALCULATIONS
    let baseXP = 0;
    const categoryXP: Record<string, number> = {};
    const categoryTotalQuestions: Record<string, number> = {};
    const categoryCompletedQuestions: Record<string, number> = {};
    
    // Total available daily questions
    const dailyQuestions = QUESTIONS.filter(q => q.type === 'daily' && q.is_active !== false && q.category_id !== "bonus" && q.category_id !== "sankalp");
    
    dailyQuestions.forEach(q => {
      const catId = q.category_id;
      if (!categoryTotalQuestions[catId]) categoryTotalQuestions[catId] = 0;
      if (!categoryCompletedQuestions[catId]) categoryCompletedQuestions[catId] = 0;
      if (!categoryXP[catId]) categoryXP[catId] = 0;
      
      categoryTotalQuestions[catId]++;
    });

    completedQuestionIds.forEach(id => {
      const q = QUESTIONS.find(q => q.id === id);
      if (q && q.type === 'daily' && q.category_id !== "bonus" && q.category_id !== "sankalp") {
        baseXP += (q.points || 0);
        const catId = q.category_id;
        if (categoryXP[catId] === undefined) categoryXP[catId] = 0;
        categoryXP[catId] += (q.points || 0);
        
        if (categoryCompletedQuestions[catId] === undefined) categoryCompletedQuestions[catId] = 0;
        categoryCompletedQuestions[catId]++;
      }
    });

    const completedCategoryIds = Object.keys(categoryTotalQuestions).filter(
      catId => categoryCompletedQuestions[catId] === categoryTotalQuestions[catId] && categoryTotalQuestions[catId] > 0
    );

    const isPerfectDay = completedCategoryIds.length === Object.keys(categoryTotalQuestions).length && Object.keys(categoryTotalQuestions).length > 0;

    // 2b. Evaluate Today's Inspiration (Category Challenge)
    const { getTodayInspiration } = await import('@/data/challenges');
    const inspiration = getTodayInspiration(date);
    let bonusXP = 0;
    
    // Check if the user completed ALL active daily niyams in the inspiration category
    if (completedCategoryIds.includes(inspiration.categoryId)) {
      const catXP = categoryXP[inspiration.categoryId] || 0;
      // Bonus is the extra XP generated by the multiplier
      bonusXP = Math.round(catXP * inspiration.multiplier) - catXP;
    }

    const finalXP = baseXP + bonusXP;

    // 3. Streak Logic
    const todayStr = date;
    const yesterdayDate = new Date(date);
    yesterdayDate.setDate(yesterdayDate.getDate() - 1);
    const yesterdayStr = yesterdayDate.toISOString().split('T')[0];
    
    let newCurrentStreak = stats.current_streak || 0;
    
    if (stats.last_submission_date === yesterdayStr) {
      newCurrentStreak += 1;
    } else if (stats.last_submission_date !== todayStr) {
      newCurrentStreak = 1;
    }

    const newBestStreak = Math.max(stats.best_streak || 0, newCurrentStreak);
    const newTotalXp = (stats.total_xp || 0) + finalXP; // Apply Final XP!
    const newDaysCompleted = (stats.days_completed || 0) + 1;
    const newTreeStage = Math.floor(newDaysCompleted / 3);

    // 4. Try RPC submission
    const { error: transactionError } = await supabase.rpc('submit_daily_niyam', {
      p_user_id: userId,
      p_submission_date: date,
      p_xp_earned: finalXP,
      p_new_total_xp: newTotalXp,
      p_new_current_streak: newCurrentStreak,
      p_new_best_streak: newBestStreak,
      p_new_days_completed: newDaysCompleted,
      p_new_tree_stage: newTreeStage,
      p_focus_id: inspiration.id
    });

    if (transactionError) {
      if (transactionError.code === '23505') {
        return { success: false, error: 'You have already submitted your Niyam for this date.' };
      }
      console.warn('RPC submit_daily_niyam failed, using direct queries fallback:', transactionError.message);

      // Direct Table Fallback
      const { error: histErr } = await supabase
        .from('daily_history')
        .insert({
          user_id: userId,
          submission_date: date,
          xp_earned: finalXP,
          submitted_at: new Date().toISOString()
        });

      if (histErr && histErr.code === '23505') {
        return { success: false, error: 'You have already submitted your Niyam for this date.' };
      }

      await supabase
        .from('user_stats')
        .upsert({
          user_id: userId,
          total_xp: newTotalXp,
          current_streak: newCurrentStreak,
          best_streak: newBestStreak,
          days_completed: newDaysCompleted,
          tree_stage: newTreeStage,
          last_submission_date: date,
          last_submission_xp: finalXP,
          updated_at: new Date().toISOString()
        });
    }

    // Return full breakdown to the frontend for the beautiful reveal animation!
    return { 
      success: true, 
      breakdown: {
        baseXP,
        bonusXP,
        finalXP,
        focusTitle: { hi: inspiration.blessingHi, en: inspiration.blessingEn },
        focusIcon: "Sparkles"
      },
      stats: {
        total_xp: newTotalXp,
        current_streak: newCurrentStreak,
        best_streak: newBestStreak,
        days_completed: newDaysCompleted,
        tree_stage: newTreeStage,
      }
    };

  } catch (error: any) {
    console.error('Submit Niyam error:', error);
    return { success: false, error: error.message || 'An unexpected error occurred.' };
  }
}

export async function checkTodaySubmissionStatus(date: string) {
  try {
    const userId = await getSession();
    if (!userId) return { success: false, submitted: false };

    // 1. Check user_stats
    const { data: stats } = await supabase
      .from('user_stats')
      .select('last_submission_date')
      .eq('user_id', userId)
      .single();

    if (stats && stats.last_submission_date === date) {
      return { success: true, submitted: true };
    }

    // 2. Check daily_history table as backup
    const { data: history } = await supabase
      .from('daily_history')
      .select('id')
      .eq('user_id', userId)
      .eq('submission_date', date)
      .limit(1);

    if (history && history.length > 0) {
      return { success: true, submitted: true };
    }

    return { success: true, submitted: false };
  } catch (error) {
    console.error('Error checking submission status:', error);
    return { success: false, submitted: false };
  }
}

